# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_issue_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='highPriority',
            field=models.BooleanField(default=False),
        ),
    ]
