# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_auto_20161031_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='kind',
            field=models.CharField(choices=[('bug', 'Bug'), ('enhancement', 'Enhancement'), ('proposal', 'Proposal'), ('task', 'Task')], default='bug', help_text='What kind of issue is this?', max_length=25),
        ),
    ]
