# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0005_issue_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='authorization',
            field=models.CharField(default='http://bitbucket.org/auth', help_text='Copy and paste the authorization url you received', max_length=150),
        ),
    ]
