# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0012_auto_20161116_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='authorization',
        ),
        migrations.AlterField(
            model_name='developer',
            name='oncall_clockin',
            field=models.TimeField(default=None, unique_for_date=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='oncall_clockout',
            field=models.TimeField(default=None, unique_for_date=True),
        ),
    ]
