# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0014_auto_20161212_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oncallrotation',
            name='username',
            field=models.CharField(max_length=40),
        ),
    ]
