# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0016_auto_20161212_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oncallrotation',
            name='oncall_clockin',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='oncallrotation',
            name='oncall_clockout',
            field=models.CharField(max_length=20),
        ),
    ]
