# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0017_auto_20161212_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oncallrotation',
            name='oncall_clockin',
            field=models.TimeField(unique_for_date=True),
        ),
        migrations.AlterField(
            model_name='oncallrotation',
            name='oncall_clockout',
            field=models.TimeField(unique_for_date=True),
        ),
    ]
