# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0018_auto_20161212_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oncallrotation',
            name='username',
        ),
        migrations.DeleteModel(
            name='OnCallRotation',
        ),
    ]
