# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0020_oncallrotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oncallrotation',
            name='oncall_clockin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='oncallrotation',
            name='oncall_clockout',
            field=models.TimeField(),
        ),
    ]
